// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwxtirzaskicmjdqzytd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13eHRpcnphc2tpY21qZHF6eXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2MDQ4ODgsImV4cCI6MjA0OTE4MDg4OH0.KuaiOTDEPANCZ4wxJuRBhaf621oLFDwk7hX21F1oERU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);